name: 'dunno yet'

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs: 
  create_release:
    name: create release
    runs-on: ubuntu-latest
    steps: 
    - name: install dependencies and libraries
      run: |
        sudo snap install godot --classic
    - name: idk yet
      run: | 
        godot --headless --export-release "WinClient" /var/builds/project
      
